dist: bionic
sudo: required
services:
- docker
language: go

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- make vet

branches:
  only:
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
  include:
  - go: "tip"
  - go: "1.14.x"
  - go: "1.15.x"
    env: GOARCH=arm
    script:
      - make build
  - go: "1.15.x"
    env: GOARCH=amd64
    script:
      - make build
