name: Tests

on:
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Build binaries
      run: make build
    - name: Run unit tests
      run: make test
    - name: Check with go vet
      run: make vet
